// Code generated by MockGen. DO NOT EDIT.
// Source: ./orders_usecase.go
//
// Generated by this command:
//
//	mockgen -source=./orders_usecase.go -destination=./mocks/orders_usecase.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "challenge_pyegros/app/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOrdersUseCase is a mock of OrdersUseCase interface.
type MockOrdersUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockOrdersUseCaseMockRecorder
	isgomock struct{}
}

// MockOrdersUseCaseMockRecorder is the mock recorder for MockOrdersUseCase.
type MockOrdersUseCaseMockRecorder struct {
	mock *MockOrdersUseCase
}

// NewMockOrdersUseCase creates a new mock instance.
func NewMockOrdersUseCase(ctrl *gomock.Controller) *MockOrdersUseCase {
	mock := &MockOrdersUseCase{ctrl: ctrl}
	mock.recorder = &MockOrdersUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrdersUseCase) EXPECT() *MockOrdersUseCaseMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockOrdersUseCase) CreateOrder(order models.Order) (*models.ResponseCreate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", order)
	ret0, _ := ret[0].(*models.ResponseCreate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockOrdersUseCaseMockRecorder) CreateOrder(order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockOrdersUseCase)(nil).CreateOrder), order)
}

// GetOrderByFilters mocks base method.
func (m *MockOrdersUseCase) GetOrderByFilters(filters models.Filters) ([]models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByFilters", filters)
	ret0, _ := ret[0].([]models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByFilters indicates an expected call of GetOrderByFilters.
func (mr *MockOrdersUseCaseMockRecorder) GetOrderByFilters(filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByFilters", reflect.TypeOf((*MockOrdersUseCase)(nil).GetOrderByFilters), filters)
}

// GetOrderByID mocks base method.
func (m *MockOrdersUseCase) GetOrderByID(orderID int64) (*models.ResponseGet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByID", orderID)
	ret0, _ := ret[0].(*models.ResponseGet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByID indicates an expected call of GetOrderByID.
func (mr *MockOrdersUseCaseMockRecorder) GetOrderByID(orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByID", reflect.TypeOf((*MockOrdersUseCase)(nil).GetOrderByID), orderID)
}

// UpdateEventOrder mocks base method.
func (m *MockOrdersUseCase) UpdateEventOrder(orderID int64, event models.Event) (*models.ResponseUpdate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEventOrder", orderID, event)
	ret0, _ := ret[0].(*models.ResponseUpdate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEventOrder indicates an expected call of UpdateEventOrder.
func (mr *MockOrdersUseCaseMockRecorder) UpdateEventOrder(orderID, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEventOrder", reflect.TypeOf((*MockOrdersUseCase)(nil).UpdateEventOrder), orderID, event)
}
